language: cpp
compiler: clang

cache:
  directories:
    - $HOME/.cache/bazel

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.16.1/bazel-0.16.1-installer-linux-x86_64.sh
  - sha256sum -c tools/bazel-0.16.1-installer-linux-x86_64.sh.sha256
  - chmod +x bazel-0.16.1-installer-linux-x86_64.sh
  - ./bazel-0.16.1-installer-linux-x86_64.sh --user
  - export PATH=$HOME/bin:$PATH

install: echo 'build --jobs=4 --curses=no --verbose_failures' >> $HOME/.bazelrc

script: bazel test -c dbg @haskell_dlist//:test

before_cache: rm -rf $HOME/.cache/bazel/_bazel_$USER/install

git:
  depth: 1
